services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
